

export const SET_FILTER= 'SET_FILTER';


export const ESTABLECER_ACCION='ESTABLECER_ACCION'



//busqueda
export const OBTENER_BUSQUEDA= 'OBTENER_BUSQUEDA';

//Carro
export const AÑADIR_CARRO= 'AÑADIR_CARRO';
export const ELIMINAR_CARRO= 'ELIMINAR_CARRO';
export const ELIMINAR_CARRO_ALL= 'ELIMINAR_CARRO_ALL';
export const OBTENER_CARRO= 'OBTENER_CARRO';
export const MODIFICAR_PRODUCTO_CARRO= 'MODIFICAR_PRODUCTO_CARRO';


