//Usuario
export const MODIFICAR_USUARIO='MODIFICAR_USUARIO';
export const OBTENER_USUARIOS= 'OBTENER_USUARIOS';
export const OBTENER_USUARIO_BY_ID= 'OBTENER_USUARIO_BY_ID';
export const SET_USER_FILTER= 'SET_USER_FILTER';
export const CAMBIO= 'CAMBIO';

//Producto
export const OBTENER_PRODUCTO_BY_CREATOR='OBTENER_PRODUCTO_BY_CREATOR';
export const REGISTRAR_PRODUCTO='REGISTRAR_PRODUCTO';
export const ELIMINAR_PRODUCTO='ELIMINAR_PRODUCTO';
export const OBTENER_PRODUCTOS='OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTO_BY_ID='OBTENER_PRODUCTO_BY_ID';
export const ESTABLECER_UBICACION='ESTABLECER_UBICACION'
export const RESTABLECER_UBICACION='RESTABLECER_UBICACION'
export const ESTABLECER_ACCION='ESTABLECER_ACCION'
export const MODIFICAR_PRODUCTO='MODIFICAR_PRODUCTO'
export const AÑADIR_PRODUCTO='AÑADIR_PRODUCTO'

//Producto
export const OBTENER_PEDIDO_BY_CREATOR='OBTENER_PEDIDO_BY_CREATOR';
export const REGISTRAR_PEDIDO='REGISTRAR_PEDIDO';
export const ELIMINAR_PEDIDO='ELIMINAR_PEDIDO';
export const OBTENER_PEDIDOS='OBTENER_PEDIDOS';
export const OBTENER_PEDIDO_BY_ID='OBTENER_PEDIDO_BY_ID';
export const MODIFICAR_PEDIDO='MODIFICAR_PEDIDO'
export const AÑADIR_PEDIDO='AÑADIR_PEDIDO'
export const INICIAR_PEDIDO='INICIAR_PEDIDO'
export const SET_VISIBLE='SET_VISIBLE'

//Producto
export const OBTENER_BANNER_BY_CREATOR='OBTENER_BANNER_BY_CREATOR';
export const REGISTRAR_BANNER='REGISTRAR_BANNER';
export const ELIMINAR_BANNER='ELIMINAR_BANNER';
export const OBTENER_BANNERS='OBTENER_BANNER';
export const OBTENER_BANNER_BY_ID='OBTENER_BANNER_BY_ID';
export const MODIFICAR_BANNER='MODIFICAR_BANNER'


//Auth
export const REGISTRO_EXITOSO= 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR= 'REGISTRO_ERROR';
export const LOGIN_EXITOSO= 'LOGIN_EXITOSO';
export const LOGIN_ERROR= 'LOGIN_ERROR';
export const OBTENER_USUARIO= 'OBTENER_USUARIO';
export const CERRAR_SESION= 'CERRAR_SESION';
export const ELIMINAR_MENSAJE= 'ELIMINAR_MENSAJE';

//alertas
export const MOSTRAR_ALERTA= 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA= 'OCULTAR_ALERTA';

//busqueda
export const OBTENER_BUSQUEDA= 'OBTENER_BUSQUEDA';

//Carro
export const AÑADIR_CARRO= 'AÑADIR_CARRO';
export const ELIMINAR_CARRO= 'ELIMINAR_CARRO';
export const ELIMINAR_CARRO_ALL= 'ELIMINAR_CARRO_ALL';
export const OBTENER_CARRO= 'OBTENER_CARRO';
export const MODIFICAR_PRODUCTO_CARRO= 'MODIFICAR_PRODUCTO_CARRO';


